### ISSUE TITLE
startup class is not packaged in a jar file

### ISSUE THREAD

**Issue by denser** [igniterealtime/Spark#11]
When i build Spark and start via Spark.exe i get this error while try to relogin.
After some workaround i get solution:

```diff
diff --git a/src/java/org/jivesoftware/MainWindow.java b/src/java/org/jivesoftware/MainWindow.java
index 77af718..1de08df 100644
--- a/src/java/org/jivesoftware/MainWindow.java
+++ b/src/java/org/jivesoftware/MainWindow.java
@@ -362,8 +362,14 @@
             return null;
         }
         if ( !jarFile.getName().endsWith(".jar") ) {
-            Log.error("The startup class is not packaged in a jar file");
-            return null;
+            if (jarFile.getName().endsWith(".exe")) {
+            	File libDir = new File(jarFile.getParentFile(), "lib");
+            	return libDir;
+			}
+            else {
+            	Log.error("The startup class is not packaged in a jar file");
+                return null;
+			}
         }
         File libDir = jarFile.getParentFile();
         return libDir;
```

**Comment by wrooot** [comment]
Please, report your issues in the forums. I'm not a developer, but i think Spark is searching for Spark.jar when starting, so it is fine when Spark is built in the official build environment (with install4j). You can have this modification for your needs, but this will not be included in the official version.

**Comment by denser** [comment]
Sorry, but this error appears aster i build Spark and try to run from build
folder too. So i am check also on install4j demo - error appears after
relogin to spark. IDK how it must be,... but seems to me Spar.exe had wrong
path to lib dir independent of installer.

May it must be fixed in other way.

Also i was searching in google such error and find some case when ppl
rebranding spark.We rebrand too. SO may be this is the reason. If you know
where to dig i would glad to fix this in other way. Thx for answer anyway.

2015-05-02 20:26 GMT+07:00 wroot <notifications@github.com>:

> Closed #11 <https://github.com/igniterealtime/Spark/issues/11>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/igniterealtime/Spark/issues/11#event-295471626>.
>



-- 
С Уважением, Денис Анатольевич.

**Comment by wrooot** [comment]
I mean, this doesn't create an issue with our official installer, so i don't think we should change anything. I'm building Spark in Netbeans or Eclipse and can run it with startup.bat just fine. You are creating your custom installer or rebranding it, so you have to do this modification. But master branch doesn't need this. At least in my understanding. Unless someone proves that this modification is ok for the master branch.

**Comment by denser** [comment]
I haven't official installer, so use demo of this to check. And if i build
from git clean - that's OK. But if I modify brand information - it become
errors in re-login. I cant understand why. I keep in mind if figure out
reason. Thanks for aiming me.

2015-05-03 0:35 GMT+07:00 wroot <notifications@github.com>:

> I mean, this doesn't create an issue with our official installer, so i
> don't think we should change anything. I'm building Spark in Netbeans or
> Eclipse and can run it with startup.bat just fine. You are creating your
> custom installer or rebranding it, so you have to do this modification. But
> master branch doesn't need this. At least in my understanding. Unless
> someone proves that this modification is ok for the master branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/igniterealtime/Spark/issues/11#issuecomment-98381855>.
>



-- 
С Уважением, Денис Анатольевич.
