### ISSUE TITLE
Roar notification multiplication

### ISSUE THREAD

**Issue by pito2901** [igniterealtime/Spark#171]
Hi everyone !

When I click on Roar notification, it opens dialog window and when I closed it, the next notification is send twice. So I click on notification, it opens dialog window again, I closed it, next notification is sent 3 times, it increases when I close this dialog window...

Thanks.

**Comment by wrooot** [comment]
This and many other issues are a result of updating Smack library to version 4. Filed as https://igniterealtime.org/issues/browse/SPARK-1755

**Comment by pito2901** [comment]
Actually I have 4.1.7 version of Smack...

**Comment by wrooot** [comment]
It doesn't matter which minor version of 4th is in use.

**Comment by wrooot** [comment]
Fixed by https://github.com/igniterealtime/Spark/pull/205
