### ISSUE TITLE
SSL Mutual Authentication (or Desktop CAC Integration Feasibility)

### ISSUE THREAD

**Issue by montj2** [igniterealtime/Spark#18]
Hi, 

Just wondering if this is on the roadmap and if not, where would be a good place to start?

**Comment by wrooot** [comment]
As Spark has no active developers currently, no, it's not on a roadmap and anyone is welcome to contribute. Can't help more with that. Not a developer myself. Study the source and try making a patch, submit a pull request here and we'll see.

**Comment by wrooot** [comment]
Closing this as there was no update for a long time and we have a separate issue tracker https://igniterealtime.org/issues/secure/Dashboard.jspa (it's read only, issues should be posted in the forums https://community.igniterealtime.org/welcome)
