### ISSUE TITLE
spark.install4j for Mac

### ISSUE THREAD

**Issue by sampang907** [igniterealtime/Spark#260]
this file seems only support for windows.
is there anyone build Mac version success?

**Comment by wrooot** [comment]
We have a forum https://community.igniterealtime.org/welcome for questions like that (this is not an Issue, and even for issues we have a JIRA tracker https://issues.igniterealtime.org/secure/Dashboard.jspa)

I don't think this file is used to produce Mac or any installers in our Bamboo production system. It uses the main build.xml file. spark.install4j file is old (still has 2.7.0 as a version number). If it doesn't work for Mac, then can't help with that. If you ask in the forums, maybe speedy could comment on that (one who has done changes to provide Mac installer for Spark again).
