### ISSUE TITLE
EMOTICONS

### ISSUE THREAD

**Issue by pauloboc** [igniterealtime/Spark#286]
PLS UPDATE PACK OF EMOTICONS

REMAKE AND NEWS EMOTICONS

IS VERY VERY OLD =(

**Comment by wrooot** [comment]
We are not designers here. If you can provide a patch with an additional emoticons set (with an appropriate open source license), be my guest. Discuss here https://community.igniterealtime.org/message/260251

**Comment by pauloboc** [comment]
Emoji One is an open source emoji project, which is available for use on sites such as Discourse.org and Slack. Images from Emoji One are available for use on any web or print project, with attribution.

---------------------------------------------------------
http://emojione.com/licensing/
---------------------------------------------------------

We can use?

**Comment by wrooot** [comment]
I suppose this is possible (just needs a link to be added somewhere on the site or in the program). So, if someone is willing to invest time and create a pack with those icons and provide a patch, we will not object it. I personally don't have time for this. Creating a pack could be time consuming.

Also, this will be ok, if you just add a pack with ~20 icons. If you want to use hundreds or more of them and have categories, then this will involve more work updating Spark to support that. I'm afraid Spark will just choke and hang trying to open that many emoticons in the picker.
