### ISSUE TITLE
No menu or exit function

### ISSUE THREAD

**Issue by MarcoH2013** [igniterealtime/Spark#297]
I did a fresh install of Spark 2.8.3 and wonder why the menu under file is not showing up?
Only menu point is "Always on top".
Also a right click on the icon does not show "exit".
My OpenFire server is running version 4.1.1.

![sparkmenu](https://cloud.githubusercontent.com/assets/6241297/22459305/51a96174-e7a0-11e6-908c-5490f08ffbbf.png)

**Comment by wrooot** [comment]
You have old version of Client Control installed on Openfire. Update it and Spark menus will show up again.
