### ISSUE TITLE
Exception in thread "Thread-35" java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParserFactory

### ISSUE THREAD

**Issue by Kaly380** [igniterealtime/Spark#30]
![fail](https://cloud.githubusercontent.com/assets/6775078/9473157/f361a172-4b1e-11e5-9c2c-8c04f24a2271.png)
Help please ..
I downloaded the code and compile and I get this error when talking to someone in the group.

Not how to solve

please

**Comment by wrooot** [comment]
Such questions should be asked in Spark forums. https://community.igniterealtime.org/community/developers/spark_dev
