### ISSUE TITLE
Problem with SSO in spark

### ISSUE THREAD

**Issue by grzew** [igniterealtime/Spark#6]
I have a client who has a problem with SSO in Spark. Sometimes spark  can't login to Openfire server using SSO. ( can't log in using SSO) Nothing can be found in spark on openfire logs. Tcpdump is showing some traffic. Other SSO features like SSO via IE to Apache basic auth is working correctly. We noticed that after removing kerberos credentials from Windows, Spark can't obtain account information. We noticed also that after using IE and login with SSO to Apache basic auth and re-opening spark, it can obtain account info and sometime we can login using sso( but not always).. Our only 100% solution is now restarting windows machine, after that SSO in spark is always working. Sometimes after some time SSO is working again without any action from our side ( but it is random, sometime few minutes, sometime few hours). This problem occurs on Spark 2.6.3 with embeded java on different Windows versions ( XP, Vista 7). Our Spark server is on CentOS and AD is on Windows 2012.

I know from my other client's that they have simmilar problem so probably this is Spark bug. Can I ask you for a help?

**Comment by wrooot** [comment]
Actually, issues should be posted in the forums, and then someone will file it in Jira.
