### ISSUE TITLE
How to build from command line?

### ISSUE THREAD

**Issue by andrey-utkin** [igniterealtime/Spark#62]
Would like to give this app a try.
I'm on Gentoo.
How should I build this to a usable Linux application?
I am considering publishing an ebuild if it works for me.

(Offtop: AFAIU Spark supports videocalls? I see screen sharing function advertised.)

**Comment by wrooot** [comment]
It is better to ask questions on the forums https://community.igniterealtime.org/welcome
Don't know how to build it for Linux There are deb and rpm packages for Spark though, and a simple tar.gz archive which also works on Linux (http://bamboo.igniterealtime.org/browse/SPARK). There is no video call support in Spark, also voice chat is currently broken. Not sure what screen sharing you are referring to. Maybe it is the Openfire Meetings plugin for Openfire, but it is not related to Spark.
