### ISSUE TITLE
Preferences menu item does nothing for me on Mac OS

### ISSUE THREAD

**Issue by jonnybradley** [igniterealtime/Spark#77]
Hi all
Using version 2.7.5 (378) the Spark -> Preferences menu item doesn't seem to do anything. All the other menu items that should make a new window seem to work fine (Start chat, Add Contact, Edit Profile etc)

Nothing in the system log, anywhere else i should check?

I'm on Mac OS 10.10.5 (14F1605) (i know, updating soon!)

Thanks

**Comment by wrooot** [comment]
It is a known issue and was reported again a few days before here https://community.igniterealtime.org/thread/57790
There is also a link to a ticket in Jira. It is better to report issues in the forums if possible. Hard to keep track of issues in different systems :)

**Comment by wrooot** [comment]
https://igniterealtime.org/issues/browse/SPARK-1192

**Comment by jonnybradley** [comment]
Thanks wrooot, wasn't aware of the other things, sorry - am new in these parts :)

**Comment by wrooot** [comment]
Fixed in the latest build http://bamboo.igniterealtime.org/browse/SPARK-NIGHTLYMAC-391/artifact/JOB1/Spark/spark_2_7_5_391.dmg
