### ISSUE TITLE
Copyright Date?

### ISSUE THREAD

**Issue by jonnybradley** [igniterealtime/Spark#78]
A very minor point, but the about window shows copyright: Ignite Realtime 2014

**Comment by wrooot** [comment]
https://igniterealtime.org/issues/browse/SPARK-1679

**Comment by wrooot** [comment]
We've decided to just remove both (c) and the year for simplicity :) https://github.com/igniterealtime/Spark/commit/ceadc0ab3e34d1b243df5911452f593e7b211371
Maybe we will find a way to add more useful information into that window later (like build number, Java/Smack version, License). Latest build http://bamboo.igniterealtime.org/browse/SPARK-NIGHTLYMAC-383/artifact/JOB1/Spark/spark_2_7_5_383.dmg
